var i18n = i18n ? i18n : {};

i18n['zh-CN'] = {
    learning: {
        common: {
            store: {
                mergeAnswerTitle: "本地有未保存的答案是否要与服务端的答案合并？",
                mergeBtn: "合并",
                ignoreBtn: "忽略",
                sureBtn: "确定"
            },
            judge: {
                right: "正确",
                error: "错误"
            },
            // 填空题翻译
            blankFilling: {
                maxWordsLength: '最多250字'
            },
            subjective: {
                attachement: "附件：",
                uploadTitle: "(最大不超过10M)",
                uploadingText: "上传中：",
                downloadAttachement: "点击下载",
                selectFileText: "请选择文件...",
                fileLimitSize: "选择的文件过大",
                sureBtn: "确定",
                uploadError: {
                    HTTP: "请求错误",
                    ABORT: "上传中止",
                    SERVER: "服务器错误",
                    ERROE_HEADER: "上传错误：",
                    INVALID_FILETYPE: "不支持的文件类型",
                    FILE_EXCEEDS_SIZE_LIMIT: "文件尺寸过大",
                    FILE_EXCEEDS_NUM_LIMIT: "超出规定文件数量",
                    ZERO_BYTE_FILE: "文件不可以为空"
                }
            },
            loading: {
                text: '正在加载'
            },
            updater: {
                noNeedToSave: "无需保存",
                saveSuccess: "保存成功",
                saveFaile: "保存失败"
            },
            explain: {
                title: '考试说明'
            },
            navigatorStat: {
                title: "本次成绩",
                accuracy: '正确率',
                right: '答对',
                question: '',
                error: '答错',
                noAnswer: '未做'
            },
            option: {
                answerTitle: '此选项为参考答案'
            },
            question: {
                temporarilyUncertain: '标记题目',
                cancelTemporarilyUncertain: "取消标记题目",
                rightAnswerLabel: '正确答案',
                answerRightTitle: '您答对了',
                subjectiveUserAnswer: '主观题用户答案',
                questionExplanation: '题目详解',
                questionsExplanation: '套题详解',
                notScore: '\t不计分',
                score: '分',
                analysisTitle: '<暂无>',
                notAnswer: '您未作答',
                subQuestionUserTitle: '您错答为',
                'goToLearn': '去学习',
                'goSubmitQuestion': '提问',
                singleChoice: '单选题',
                multipleChoice: '多选题',
                indefiniteChoice: '不定项选择题',
                completion: '填空题',
                subjectivity: '主观题',
                judgment: '判断题',
                matching: '连线题',
                complex: '套题',
                noMarkTitle: '未批改',
                answerWrongTitle: "您答错了",
                questionType: {
                    nd_linkup: "连连看",
                    interactive: '互动题',
                    base: '基础题',
                    ndLinkupOld: "连连看",
                    ndOrder: "排序题",
                    ndProbabilitycard: "概率卡牌",
                    fraction: "分式加减",
                    memorycard: "记忆卡片题",
                    classified: "分类题型",
                    table: "分类表格题",
                    pointsequencing: "点排序题",
                    arithmetic: "竖式计算题",
                    textselect: "文本选择题",
                    magicbox: "魔方盒游戏",
                    wordpuzzle: "字谜游戏题",
                    guessword: "猜词游戏",
                    fillblank: "选词填空题",
                    compare: "比大小",
                    "nd_section_evaluating": "英语篇章发音评测",
                    "nd_sentence_evaluat": "英语句子发音评测",
                    "nd_enoral_word": "英语口语单词",
                    "nd_enoral_sentence": "英语口语句子",
                    "nd_enoral_paragraph": "英语口语段落",
                    "nd_enoral_dialogue": "英语口语对话",
                    "nd_enoral_composition": "英语口语作文"
                },
                gotoAnswer: '去答题',
                gotoViewAnswer: '去查看答案',
                'commit': '确定',
                "next": "下一题",
                edit: "编辑",
                cancel: "取消",
                questionBank: {
                    "addErrorReason": "+添加错因",
                    "makeEmphasis": "标记为重点",
                    "cancelEmphasis": "取消标记为重点",
                    "addToQuestionBank": "加入错题本",
                    "inQuestionBank": "已加入错题本",
                    "errorReason": "错因",
                    "createErrorReason": "创建",
                    "enterErrorReason": "请输入错因",
                    "editReasonBtnTitlt": "完成",
                    "headerTitle": "查看错误原因",
                    "systemTitle": "系统提示",
                    "deleteTitle": "确认删除？",
                    "note": "笔记",
                    "noteTitle": "写下对这道题心得感想吧~"
                },
                "gotoLearn": "去学习",
                "quiz": "提问"
            },
            navigation: "答题卡",
            pullUp: "收起",
            expand: "展开答题卡",
            prev: "<i></i>上一题",
            next: "<i></i>下一题",
            submit: "提交练习"
        },
        exam: {
            answer: {
                sure: '确定',
                retry: '重试',
                explanation: '试卷说明',
                msg1: '已完成全部题目，确定交卷吗？',
                msg2: "已完成 {{doneCount}} 题，还有 {{noAnswerCount}} 题未做，确定交卷吗？",
                msg3: "已完成 {{doneCount}} 题，还有 {{noAnswerCount}} 题未做，不能交卷！",
                commitExam: '交卷',
                commitFail: '交卷失败',
                continueAnswer: '继续答题',
                examFinishTitle: "本次考试时间已到, 不能继续答题",
                examAutoCommitTitle: "本次考试已自动交卷，不能继续作答！",
                confirmCaption: "系统提示"
            },
            header: {
                residualTime: '剩余用时',
                costTime: '考试用时',
                saveTitle: '保存答案',
                save: '保存'
            },
            parts: {
                buttonTitle: '点击可切换'
            },
            prepare: {
                perTitle: "每",
                weekTitle: "周",
                perMonthTitle: "每月",
                dayTitle: "日 ",
                week: {
                    seven: "日",
                    six: "六",
                    five: "五",
                    four: "四",
                    three: "三",
                    two: "二",
                    one: "一"
                },
                questionNumber: '题数',
                passAccuracy: '正确率要求',
                examQNum: "考试题数",
                passScore: "及格分",
                examTimeLength: "考试时长",
                back: '< 返回',
                question: '题',
                totalScore: '总分',
                pass: '及格',
                minute: '分钟',
                caution: '注意',
                attachements: "附件",
                download: "下载",
                timeHint: '距离考试结束：',
                examStartTime: "考试开始时间：",
                cautionItem1: '1、开始考试后不可暂停，时间到后自动交卷，请注意时间安排。',
                cautionItem2: '2、答题结束，点击“交卷”完成当前考试。',
                examFinishTitle: '考试已结束',
                examEndTitle: '距离考试结束还有：',
                examStartTitle: '距离开考还有：',
                examStartedTitle: '考试已开始：',
                examFinished: '本次考试时间已到, 不能继续答题',
                commit: '交卷',
                sureBtn: "确定",
                confirmCaption: "系统提示",
                notSupport: {
                    subType2: "闯关请到移动端体验！",
                    subType3: "竞赛请到移动端体验！<br>99u中的体验路径为：【学习】-【测评中心】-【智力竞赛】"
                },

                hours: '小时',
                minutes: '分',
                seconds: '秒',
                score: '分',
                noEndTime: '不限',
                examTimeTitle: "考试时间",
                examSummary: "考试介绍",
                bestScore: "最高分：",
                lastAnswer: "上次结果：",
                noBestScore: "未统计",
                historyScore: "历史成绩",
                viewAnalysis: "查看解析",
                toText: "至",
                examStatus: {
                    ended: "考试已结束",
                    disabled: "考试不可用",
                    goon: "继续考试",
                    'continue': "继续考试",
                    noRetryTimes: "无考试机会",
                    wait: "即将开始",
                    start: "开始考试",
                    retry1: "重新考试（剩",
                    retry2: "次机会）",
                    waitingPerusal: "待批改",
                    enrollNow: '立即报名',
                    //待审核
                    pendingAudit: '待审核',
                    //审核拒绝
                    rejectAudit: '审核拒绝',
                    //未报名
                    notEnroll: '未报名',
                    reEnrollNow: "重新报名",
                    retryNoLimit: "重新考试（不限次数）",
                    paying: "待付款",
                    nextExam: "下一场  ",
                    bestResult: '最佳成绩',
                    openClient: '打开客户端'
                },
                ranking: "排行榜",
                reason: "原因: ",
                toMobile: "请到移动端app体验",
                collection: "收藏",
                cancelCollection: "取消收藏",
                collectionFail: "失败，请重试!",
                detection: "音频试听"
            },
            end: {
                back: '< 返回',
                objectiveQuestionsTile: "客观题",
                score: "分",
                subjectQuestionTitle: "，主观题待批改",
                analysisTitle: "答案解析",
                testResult: "你的测试结果：",
                consuming: "考试用时",
                passingScore: "及格分数",
                totalScore: "总分",
                retryTitle2: "次）",
                retryTitle1: "再考一次（剩",
                hours: '小时',
                minutes: '分钟',
                seconds: '秒',
                examEndPage: '考试结果',
                ranking: '排行榜',
                retryNoLimit: "重新考试（不限次数）",
                seeTips: "查看秘笈",
                remainingChanceNotEnough: "考试机会已用完",
                accuracy: '正确率',
                passAccuracy: '达标正确率',
                totalQuestionNum: '总题数',
                questionTitle: '题',
                submitPaper: '交卷',
                passRequirement: '达标要求'
            },
            exception: {
                message: "<br/><span>如有问题请联系客服，给您带来不便请见谅。</span>",
                back: "< 返回",
                title: '考试异常页'
            },
            history: {
                historyScorePage: '历史成绩',
                involvementTimeTitle: '考试时间',
                totalScoreTitle: '总&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;分：',
                passScoreTitle: '及&nbsp;&nbsp;格&nbsp;分：',
                tryTimesTitle: '考试次数：',
                bestScoreTitle: '最&nbsp;&nbsp;高&nbsp;&nbsp;分：',
                questionNumTitle: '题&nbsp;&nbsp;&nbsp;量：',
                timeConsumingTitle: '考试用时',
                durationTitle: '考试时长：',
                viewAnalysisTitle: '查看解析',
                viewAnalysisAndResult: '查看解析和结果',
                viewResult: '查看结果',
                isPassTitle: '是否通过',
                questionTitle: '题',
                passedTitle: '已通过',
                noPassTitle: '未通过',
                tableScoreHeaderTitle: '分数',
                scoreTitle: "分",
                hoursTitle: '小时',
                minutesTitle: '分钟',
                secondsTitle: '秒',
                noData: "暂无数据",
                bestResult: '最佳成绩：',
                passModel: '通过方式：',
                passRequirement: '达标要求：',
                questionNumber: '总题数：',
                accuracy: '正确率(%)',
                scorePassModel: '分数',
                submitPaper: '交卷',
                back: '返回'
            },
            ranking: {
                rankingList: "排行榜",
                myRanking: "我的排名",
                ranking: '排名',
                user: "用户",
                costTime: '用时',
                bestScore: '最高分',
                loadMore: '点击加载更多排名...',
                loading: '加载中...',
                nodata: '快参加考试，冲上榜单吧！',
                hours: '小时',
                minutes: '分',
                seconds: '秒',
                position: "位",
                notAttend: "您还没有成绩"
            }
        },
        exercise: {
            answer: {
                commit: '提交练习',
                reAnswer: '重新练习',
                explanation: '练习说明',
                exerciseScore: '本次成绩',
                noAnswer: "很抱歉！您尚未答题，不能提交答案。",
                continueAnswer: '继续答题',
                answerAllCommitTitle: "已完成全部题目，确定提交答案吗？",
                examAutoCommitTitle: "本次练习已自动交卷，不能继续作答！",
                sure: '确定',
                cancel: '取消',
                partialFinishCommitTitle: "已完成 {{doneCount}} 题，还有 {{noAnswer}} 题未做，确定提交答案吗？",
                partialFinishCommitTitle2: "已完成 {{doneCount}} 题，还有 {{noAnswer}} 题未做，不能提交答案！",
                questionBank: {
                    reasonEmpty: "错因不能为空"
                },
                see: '我知道了',
                wrongBook: '做错的题目将自动记录到“错题本”中，可以查看并练习哦！'
            },
            prepare: {
                totalQuestion: '本练习共 {{totalCount}} 题',
                startAnswer: '开始练习',
                bestScoreCaption: '最好成绩：',
                right: '答对',
                question: '题',
                error: '答错',
                noAnswer: '未答',
                accuracy: '正确率',
                toMobile: "请到移动端app体验"
            }
        },
        singleModeExam: {
            answer: {
                commit: '交卷',
                reAnswer: '重新考试',
                explanation: '考试说明',
                exerciseScore: '本次成绩',
                noAnswer: "很抱歉！您尚未答题，不能提交答案。",
                continueAnswer: '继续答题',
                answerAllCommitTitle: "已完成全部题目，确定提交答案吗？",
                examAutoCommitTitle: "本次考试已自动交卷，不能继续作答！",
                sure: '确定',
                cancel: '取消',
                partialFinishCommitTitle: "已完成 {{doneCount}} 题，还有 {{noAnswer}} 题未做，确定提交答案吗？",
                partialFinishCommitTitle2: "已完成 {{doneCount}} 题，还有 {{noAnswer}} 题未做，不能提交答案！",
            },
            prepare: {
                totalQuestion: '本考试共 {{totalCount}} 题',
                startAnswer: '开始考试',
                bestScoreCaption: '最好成绩：',
                right: '答对',
                question: '题',
                error: '答错',
                noAnswer: '未答',
                accuracy: '正确率',
                toMobile: "请到移动端app体验"
            }
        }
    }
};

i18n['en-US'] = {
    learning: {
        common: {
            store: {
                mergeAnswerTitle: "Local answers have not been saved yet. Do you want to merge them with the server answers?",
                mergeBtn: "Merge",
                ignoreBtn: "Ignore",
                sureBtn: "Ok"
            },
            judge: {
                right: "correct",
                error: "worng"
            },
            blankFilling: {
                maxWordsLength: 'max. 250 words!'
            },
            subjective: {
                attachement: "Attachement:",
                uploadTitle: "(The maximum does not exceed 10MB)",
                uploadingText: "uploading:",
                downloadAttachement: "click to download",
                selectFileText: "select file...",
                fileLimitSize: "file limit size",
                sureBtn: "OK",
                uploadError: {
                    HTTP: "Request error!",
                    ABORT: "Uploading is terminated.",
                    SERVER: "Server error.",
                    ERROE_HEADER: "Error: ",
                    INVALID_FILETYPE: "File type is not supported.",
                    FILE_EXCEEDS_SIZE_LIMIT: "File size is exceed.",
                    FILE_EXCEEDS_NUM_LIMIT: "File count is exceed.",
                    ZERO_BYTE_FILE: "File cannot be empty."
                }
            },
            loading: {
                text: 'loading'
            },
            updater: {
                noNeedToSave: "No need to save",
                saveSuccess: "Save success",
                saveFaile: "Save faile"
            },
            explain: {
                title: 'Explanation'
            },
            navigatorStat: {
                title: "The score of this time",
                accuracy: 'Accuracy',
                right: 'Right:',
                question: '',
                error: 'Error:',
                noAnswer: 'N/A:'
            },
            option: {
                answerTitle: 'This option is the reference answer'
            },
            questionOption: {
                answerTitle: 'This option is the reference answer'
            },
            question: {
                temporarilyUncertain: 'Temporarily Uncertain',
                cancelTemporarilyUncertain: "Cancel Mark",
                rightAnswerLabel: 'Correct Answer',
                answerRightTitle: 'Your\'s answer is right.',
                subjectiveUserAnswer: 'Subjective question user answer',
                questionExplanation: 'Subject explanation',
                questionsExplanation: 'A set of questions',
                notScore: '\t(no score)',
                score: 'score',
                analysisTitle: '<N/A>',
                notAnswer: 'You did not answer',
                subQuestionUserTitle: 'You are wrong to',
                'goToLearn': 'Learn',
                'goSubmitQuestion': 'Question',
                singleChoice: 'Single-Choice',
                multipleChoice: 'Multi-Choice',
                indefiniteChoice: 'Indefinite-Choice',
                completion: 'Blank-Filling',
                subjectivity: 'Open-Question',
                judgment: 'True/False',
                matching: 'Matching',
                complex: 'Complex',
                noMarkTitle: 'Un mark',
                answerWrongTitle: "Your are wrong",
                questionType: {
                    nd_linkup: "Link up",
                    interactive: 'Interactive Question',
                    base: 'Base Question',
                    ndLinkupOld: "Link Up",
                    ndOrder: "Order",
                    ndProbabilitycard: "Probability Card",
                    fraction: "Fraction",
                    memorycard: "Memory Card",
                    classified: "Classified",
                    table: "Table",
                    pointsequencing: "Point Sequencing",
                    arithmetic: "Arithmetic",
                    textselect: "Text Select",
                    magicbox: "Magic Box",
                    wordpuzzle: "Word Puzzle",
                    guessword: "Guess Word",
                    fillblank: "Fill Blank",
                    compare: "Compare",
                    "nd_section_evaluating": "Section Evaluating",
                    "nd_sentence_evaluat": "Sentence Evaluat",
                    "nd_enoral_word": "Enoral Word",
                    "nd_enoral_sentence": "Enoral Sentence",
                    "nd_enoral_paragraph": "Enoral Paragraph",
                    "nd_enoral_dialogue": "Enoral Dialogue",
                    "nd_enoral_composition": "Enoral Composition"
                },
                gotoAnswer: 'Go to answer',
                gotoViewAnswer: 'Go to view answer',
                'commit': 'Confirm',
                "next": "Next",
                edit: "编辑_en",
                cancel: "取消_en",
                questionBank: {
                    "addErrorReason": "+添加错因_en",
                    "makeEmphasis": "标记为重点_en",
                    "cancelEmphasis": "取消标记为重点_en",
                    "addToQuestionBank": "加入错题本_en",
                    "inQuestionBank": "已加入错题本_en",
                    "errorReason": "错因_en",
                    "createErrorReason": "创建_en",
                    "enterErrorReason": "请输入错因_en",
                    "editReasonBtnTitlt": "完成_en",
                    "headerTitle": "查看错误原因_en",
                    "systemTitle": "系统提示_en",
                    "deleteTitle": "确认删除？_en",
                    "note": "笔记_en",
                    "noteTitle": "写下对这道题心得感想吧~ _en"
                },
                "gotoLearn": "去学习_en",
                "quiz": "提问_en"
            },
            navigation: "Navigator",
            pullUp: "Pull Up",
            expand: "EXPAND",
            prev: "<i></i>Prev",
            next: "<i></i>Next",
            submit: "Submit",
            detection: "detection"
        },
        exam: {
            answer: {
                sure: 'OK',
                retry: 'retry',
                explanation: 'Explanation',
                msg1: "You have answered all questions. Confirm to submit?",
                msg2: "You have answered {{doneCount}} questions. {{noAnswerCount}} question(s) is(are) left. Confirm to submit?",
                msg3: "You hae answered {{doneCount}} questions. {{noAnswerCount}} question(s) is(are) left. Do not allowed to submit!",
                commitExam: 'Commit',
                commitFail: 'Commit Fail',
                continueAnswer: 'Cancel',
                examFinishTitle: "Time out, can not continue answer",
                examAutoCommitTitle: "Has been auto commit，can't continue answer!",
                confirmCaption: "System Tip"
            },
            header: {
                residualTime: 'residual time',
                costTime: 'cost time',
                saveTitle: 'save answer',
                save: 'Save'
            },
            parts: {
                buttonTitle: 'click to switch'
            },
            prepare: {
                perTitle: "Every Week Of ",
                weekTitle: "",
                perMonthTitle: "Days Of ",
                dayTitle: " Every Month",
                week: {
                    seven: "Sunday",
                    six: "Saturday",
                    five: "Friday",
                    four: "Thursday",
                    three: "Wednesday",
                    two: "Tuesday",
                    one: "Monday"
                },
                questionNumber: 'Question Num',
                passAccuracy: 'Required accuracy',
                examQNum: "Question Num",
                passScore: "Pass Score",
                examTimeLength: "Duration",
                back: '< back',
                question: 'Questions',
                totalScore: 'Full Marks',
                pass: 'Pass',
                minute: 'Minutes',
                caution: 'Caution',
                attachements: "Attachements",
                download: "Download",
                timeHint: 'The end of the distance test:',
                examStartTime: "Time left: ",
                cautionItem1: '1. Exam can not be interrupted after starting. Please notice the countdown at the top-right.',
                cautionItem2: '2.When you finish paper, please click "Submit" button to hand your answers.',
                examFinishTitle: 'Exam has been Finished',
                examEndTitle: 'Time left : ',
                examStartTitle: 'From the start of the examination and:',
                examStartedTitle: 'The exam left: ',
                examFinished: 'Time out, can not continue to answer',
                commit: 'commit',
                sureBtn: "Ok",
                confirmCaption: "System Tip",
                notSupport: {
                    subType2: "Please go to the mobile device experience! ",
                    subType3: "Please go to the mobile device experience! <br>99u in the experience of the path: 【Learning】 - 【Exam Center】 - 【Quiz】",
                },

                hours: ' h ',
                minutes: ' m ',
                seconds: ' s',
                score: ' score',
                noEndTime: ' infinite ',
                examTimeTitle: "Exam Time:",
                examSummary: "Summary:",
                bestScore: "Best Score :  ",
                lastAnswer: "Last Answer : ",
                noBestScore: "No data",
                historyScore: "History Score",
                viewAnalysis: "Analysis",
                toText: " To ",
                examStatus: {
                    ended: "Exam Ended",
                    disabled: "Exam Disabled",
                    goon: "Continue",
                    'continue': "Continue",
                    noRetryTimes: "No Try Times",
                    wait: "Wait",
                    start: "Start",
                    retry1: "Retry (Left: ",
                    retry2: " Times)",
                    waitingPerusal: "Waiting perusal",
                    enrollNow: 'Enroll now',
                    //待审核
                    pendingAudit: 'Unconfirmed',
                    //审核拒绝
                    rejectAudit: 'Rejected',
                    notEnroll: 'Not Enroll',
                    reEnrollNow: "Re enroll now",
                    retryNoLimit: "Retry",
                    paying: "Pay",
                    nextExam: "Next Session ",
                    openClient: 'Open Exam Client'
                },
                ranking: "Leaderboard",
                reason: "Tips: ",
                toMobile: "Please go to the mobile terminal app experience",
                collection: "Favorite",
                cancelCollection: "Cancel Favorite",
                collectionFail: "Failure, try again!",
                bestResult: 'Best result: '
            },
            end: {
                back: '< back',
                objectiveQuestionsTile: " Objective ",
                score: " score ",
                subjectQuestionTitle: "，Subjective wait for correcting",
                analysisTitle: "Analysis",
                testResult: "Your test result：",
                consuming: "cost time",
                passingScore: "pass score",
                totalScore: "total score",
                retryTitle2: " Times)",
                retryTitle1: "Retry (Left: ",
                hours: ' hours',
                minutes: ' minutes ',
                seconds: ' seconds ',
                examEndPage: 'Exam Result',
                ranking: "Leaderboard",
                retryNoLimit: "Retry",
                seeTips: "Seetips",
                remainingChanceNotEnough: "No test opportunities",
                accuracy: 'Accuracy',
                passAccuracy: 'Required Accuracy',
                totalQuestionNum: 'Question Num',
                questionTitle: '',
                submitPaper: 'Submit',
                passRequirement: 'Pass Level'
            },
            exception: {
                message: "<br/><span>If you have any questions please contact customer service, to bring you the same please forgive me.</span>",
                back: "< back",
                title: 'Exam exception'
            },
            history: {
                historyScorePage: 'History Score',
                involvementTimeTitle: 'Involvement Time',
                totalScoreTitle: 'Total Score:',
                passScoreTitle: 'Pass Score:',
                tryTimesTitle: 'Exam Chance:',
                bestScoreTitle: 'Best Score:',
                questionNumTitle: 'Question Num:',
                timeConsumingTitle: 'Time Consuming',
                durationTitle: 'Duration:',
                viewAnalysisTitle: 'View Analysis',
                viewAnalysisAndResult: 'View Analysis And Result',
                viewResult: 'Check Result',
                isPassTitle: 'Passed',
                questionTitle: '',
                passedTitle: 'Passed',
                noPassTitle: 'No Pass',
                tableScoreHeaderTitle: 'Score',
                scoreTitle: "Score",
                hoursTitle: ' hour ',
                minutesTitle: ' minue ',
                secondsTitle: ' second ',
                noData: "No Data",
                bestResult: 'Best Result：',
                passModel: 'Pass Model：',
                passRequirement: 'Pass Level：',
                questionNumber: 'Question Num：',
                accuracy: 'Accuracy',
                scorePassModel: 'Score',
                submitPaper: 'submit',
                back: 'back'
            },
            ranking: {
                myRanking: "My Ranking",
                rankingList: "Ranking List",
                ranking: 'Ranking',
                user: "User Name",
                costTime: 'Cost Time',
                bestScore: 'Best Score',
                loadMore: 'Load More...',
                loading: 'Loading...',
                nodata: 'No Data',
                hours: ' hour ',
                minutes: ' minute ',
                seconds: ' second ',
                position: "",
                notAttend: "No score"
            }
        },
        exercise: {
            answer: {
                commit: 'Commit',
                reAnswer: 'Re Answer',
                explanation: 'explanation',
                exerciseScore: 'The score of this time',
                noAnswer: "Sorry! You have dit not answer, you can not submit the answer.",
                continueAnswer: 'Contine',
                answerAllCommitTitle: "You have answered all questions. Confirm to submit?",
                examAutoCommitTitle: "Has been auto commit，can't continue answer!",
                sure: 'OK',
                cancel: 'cancel',
                partialFinishCommitTitle: "You have answered {{doneCount}} questions. {{noAnswer}} question(s) is(are) left. Confirm to submit?",
                partialFinishCommitTitle2: "You have answered {{doneCount}} questions. {{noAnswer}} question(s) is(are) left. Do not allowed to submit!",
                questionBank: {
                    reasonEmpty: "reason must be not empty"
                },
                see: 'I see',
                wrongBook: 'The wrong question will automatically record to "the error", you can view and practice!'
            },
            prepare: {
                totalQuestion: 'total {{totalCount}} question',
                startAnswer: 'Start',
                bestScoreCaption: 'best score:',
                right: 'right',
                question: 'question',
                error: 'error',
                noAnswer: 'don\'t answer',
                accuracy: 'accuracy',
                toMobile: "Please go to the mobile terminal app experience"
            }
        },
        singleModeExam: {
            answer: {
                commit: 'Commit',
                reAnswer: 'Re Answer',
                explanation: 'explanation',
                exerciseScore: 'The score of this time',
                noAnswer: "Sorry! You have dit not answer, you can not submit the answer.",
                continueAnswer: 'Contine',
                answerAllCommitTitle: "You have answered all questions. Confirm to submit?",
                examAutoCommitTitle: "Has been auto commit，can't continue answer!",
                sure: 'OK',
                cancel: 'cancel',
                partialFinishCommitTitle: "You have answered {{doneCount}} questions. {{noAnswer}} question(s) is(are) left. Confirm to submit?",
                partialFinishCommitTitle2: "You have answered {{doneCount}} questions. {{noAnswer}} question(s) is(are) left. Do not allowed to submit!",
            },
            prepare: {
                totalQuestion: 'total {{totalCount}} question',
                startAnswer: 'Start',
                bestScoreCaption: 'best score:',
                right: 'right',
                question: 'question',
                error: 'error',
                noAnswer: 'don\'t answer',
                accuracy: 'accuracy',
                toMobile: "Please go to the mobile terminal app experience"
            }
        }
    }
};
